version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "9080:8080"
    environment:
      - AWS_CBOR_DISABLE=1
      - USE_SSL=true
      - SERVICES=kinesis
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
